# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_matcher/testdata/test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto_matcher/testdata/test.proto\x12\rproto_matcher\"\xaa\x01\n\x03\x46oo\x12 \n\x04\x62\x61rs\x18\x01 \x03(\x0b\x32\x12.proto_matcher.Bar\x12\x1f\n\x03\x62\x61z\x18\x02 \x01(\x0b\x32\x12.proto_matcher.Baz\x12\x30\n\x07mapping\x18\x03 \x03(\x0b\x32\x1f.proto_matcher.Foo.MappingEntry\x1a.\n\x0cMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa8\x01\n\x03\x42\x61r\x12\x12\n\x08short_id\x18\x01 \x01(\x05H\x00\x12\x11\n\x07long_id\x18\x02 \x01(\x03H\x00\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\x10\n\x08progress\x18\x06 \x01(\x02\x12\x11\n\tprecision\x18\x07 \x01(\x01\x12\x0f\n\x07\x63hecked\x18\x08 \x01(\x08\x12\r\n\x05notes\x18\t \x03(\tB\x04\n\x02id\"f\n\x03\x42\x61z\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.proto_matcher.Baz.Status\"4\n\x06Status\x12\x17\n\x13STATUS_UNSPECIFITED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_matcher.testdata.test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOO_MAPPINGENTRY._options = None
  _FOO_MAPPINGENTRY._serialized_options = b'8\001'
  _globals['_FOO']._serialized_start=53
  _globals['_FOO']._serialized_end=223
  _globals['_FOO_MAPPINGENTRY']._serialized_start=177
  _globals['_FOO_MAPPINGENTRY']._serialized_end=223
  _globals['_BAR']._serialized_start=226
  _globals['_BAR']._serialized_end=394
  _globals['_BAZ']._serialized_start=396
  _globals['_BAZ']._serialized_end=498
  _globals['_BAZ_STATUS']._serialized_start=446
  _globals['_BAZ_STATUS']._serialized_end=498
# @@protoc_insertion_point(module_scope)
